# Code of Conduct {#code}

A _Code of Conduct_ is a set of basic ground rules that we ask participants in lab spaces to follow. The goal is to create an open and inclusive space for our work that helps us achieve our collective goals. Along with our lab culture/philosophy, it also provides a benchmark for self-evaluation and helps better define our identity as a community. 

__We expect all lab members to adhere to the policies and guidelines outlined here.__  



## Short version

The Farré lab is dedicated to providing a harassment-free experience for everyone, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, age, race, or religion. We do not tolerate harassment of participants in any form and prioritize marginalised people’s safety over privileged people’s comfort.  

This code of conduct applies to all Farré lab spaces, including group and individual meetings (face to face and remote), workshops, social events, email correspondence, and web channels and code repositories, both online and off. Anyone who violates this code of conduct may be referred to the university’s academic policies.


## Longer version



### Reporting





### Additional resources


